import { useEffect, useState } from "react";
type Member = {staffId:string;name:string;service:string;source:string};
type Audit = {checkedAt:string;counts:Record<string,number>;nominalStatus:Record<string,number>;sameDni:{name:string;people:Member[]}[];sameFullName:{name:string;people:Member[]}[];surnameCandidates:{name:string;service:string;candidates:{name:string;service:string}[]}[];mismatches:{name:string;appService:string;fileService:string;row:number;fields:string[]}[]};
export function PersonalSourceAudit() {
  const [report,setReport]=useState<Audit|null>(null),[error,setError]=useState("");
  useEffect(()=>{ let active=true; void fetch("/api/personal/source-audit").then(async(r)=>{if(!r.ok)throw new Error("La comparación de fuentes no está disponible.");return r.json();}).then((r)=>{if(active)setReport(r);}).catch((e)=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
  if(error)return <p role="alert">{error}</p>;
  if(!report)return <p role="status">Cargando revisión de nómina…</p>;
  return <section className="space-y-4 rounded-2xl bg-surface p-4 shadow-[var(--shadow-border)]">
    <h2 className="text-xl font-semibold">Revisión de identidad y servicios</h2>
    <p className="text-sm text-muted">Comparación realizada {new Date(report.checkedAt).toLocaleString("es-AR")}. Es una revisión de las fuentes importadas, no una consulta a una nómina actual de Recursos Humanos.</p>
    <p>{report.counts.imported} fichas importadas de {report.counts.xlsx} filas del Excel y {report.counts.csv} del CSV. {report.counts.missing} filas faltantes. {report.counts.sourceDisagreements} diferencias entre los archivos. {report.counts.sourceServiceReview} diferencias de servicio entre LISTADO y LISTADO_UNICO.</p>
    <div className="rounded-xl border border-warn/40 bg-warn-soft p-3"><p className="font-medium">No se fusionaron ni reasignaron personas automáticamente.</p><p className="mt-1 text-sm">El mismo apellido no prueba identidad. Figurar en otra área puede ser correcto. Se conservan las fichas y los cronogramas hasta verificar cada coincidencia.</p></div>
    <details open><summary className="cursor-pointer font-semibold">Mismo DNI ({report.sameDni.length} pares o conjuntos)</summary><ul className="mt-2 space-y-3">{report.sameDni.map((group,i)=><li key={i} className="rounded-lg border border-border p-3"><strong>{group.name}</strong>{group.people.map((p)=><p key={p.staffId} className="text-sm">{p.name} · {p.service}</p>)}</li>)}</ul></details>
    <details><summary className="cursor-pointer font-semibold">Mismo nombre completo ({report.sameFullName.length} conjuntos)</summary><ul className="mt-2 space-y-3">{report.sameFullName.map((group,i)=><li key={i} className="rounded-lg border border-border p-3"><strong>{group.name}</strong>{group.people.map((p)=><p key={p.staffId} className="text-sm">{p.name} · {p.service} · {p.source}</p>)}</li>)}</ul></details>
    <details><summary className="cursor-pointer font-semibold">Fichas con apellido solamente ({report.surnameCandidates.length})</summary><p className="my-2 text-sm">No se pueden unir con certeza. Coincidencias posibles para revisar, no identidades confirmadas.</p><ul className="space-y-3">{report.surnameCandidates.map((p,i)=><li key={i} className="rounded-lg border border-border p-3"><strong>{p.name} · {p.service}</strong>{p.candidates.map((c,j)=><p className="text-sm" key={j}>{c.name} · {c.service}</p>)}</li>)}</ul></details>
    <details open><summary className="cursor-pointer font-semibold">Datos distintos de la fuente ({report.mismatches.length})</summary>{report.mismatches.map((p,i)=><p key={i} className="mt-2 text-sm">Fila {p.row}: {p.name}. Revisar: {p.fields.join(", ")}. Servicio de la app: {p.appService}. Servicio del archivo: {p.fileService}.</p>)}</details>
    <details><summary className="cursor-pointer font-semibold">Referencia de nómina 2023</summary><ul className="mt-2 text-sm">{Object.entries(report.nominalStatus).map(([status,count])=><li key={status}>{status}: {count}</li>)}</ul><p className="mt-2 text-sm text-muted">Esta referencia histórica no confirma que una persona siga trabajando hoy en el hospital.</p></details>
  </section>;
}
