/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchivoRouteImport } from './routes/archivo'
import { Route as CambiosRouteImport } from './routes/cambios'
import { Route as ComplementosRouteImport } from './routes/complementos'
import { Route as ComunicacionesRouteImport } from './routes/comunicaciones'
import { Route as ContinuidadRouteImport } from './routes/continuidad'
import { Route as InternadosRouteImport } from './routes/internados'
import { Route as PersonalMapaRouteImport } from './routes/personal-mapa'
import { Route as PlantelRouteImport } from './routes/plantel'
import { Route as SaludRouteImport } from './routes/salud'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as ArchivoIndexRouteImport } from './routes/archivo.index'
import { Route as ArchivoIdRouteImport } from './routes/archivo.$id'
import { Route as ContinuidadIndexRouteImport } from './routes/continuidad.index'
import { Route as ContinuidadAhoraRouteImport } from './routes/continuidad.ahora'
import { Route as ContinuidadClimaRouteImport } from './routes/continuidad.clima'
import { Route as ContinuidadConfigRouteImport } from './routes/continuidad.config'
import { Route as ContinuidadHistorialRouteImport } from './routes/continuidad.historial'
import { Route as ContinuidadMapaRouteImport } from './routes/continuidad.mapa'
import { Route as ContinuidadPlanRouteImport } from './routes/continuidad.plan'
import { Route as ContinuidadTransporteRouteImport } from './routes/continuidad.transporte'
import { Route as ContinuidadTurnoRouteImport } from './routes/continuidad.turno'
import { Route as FichaIdRouteImport } from './routes/ficha.$id'
import { Route as InternadosIndexRouteImport } from './routes/internados.index'
import { Route as InternadosSlugRouteImport } from './routes/internados.$slug'
import { Route as InternadosAlertasRouteImport } from './routes/internados.alertas'
import { Route as InternadosCamasRouteImport } from './routes/internados.camas'
import { Route as InternadosCapturaRouteImport } from './routes/internados.captura'
import { Route as InternadosPacientesRouteImport } from './routes/internados.pacientes'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosSlugRouteImport } from './routes/servicios.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivoRoute = ArchivoRouteImport.update({
  id: '/archivo',
  path: '/archivo',
  getParentRoute: () => rootRouteImport,
} as any)
const CambiosRoute = CambiosRouteImport.update({
  id: '/cambios',
  path: '/cambios',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplementosRoute = ComplementosRouteImport.update({
  id: '/complementos',
  path: '/complementos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicacionesRoute = ComunicacionesRouteImport.update({
  id: '/comunicaciones',
  path: '/comunicaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinuidadRoute = ContinuidadRouteImport.update({
  id: '/continuidad',
  path: '/continuidad',
  getParentRoute: () => rootRouteImport,
} as any)
const InternadosRoute = InternadosRouteImport.update({
  id: '/internados',
  path: '/internados',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalMapaRoute = PersonalMapaRouteImport.update({
  id: '/personal-mapa',
  path: '/personal-mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantelRoute = PlantelRouteImport.update({
  id: '/plantel',
  path: '/plantel',
  getParentRoute: () => rootRouteImport,
} as any)
const SaludRoute = SaludRouteImport.update({
  id: '/salud',
  path: '/salud',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivoIndexRoute = ArchivoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArchivoRoute,
} as any)
const ArchivoIdRoute = ArchivoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArchivoRoute,
} as any)
const ContinuidadIndexRoute = ContinuidadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContinuidadRoute,
} as any)
const ContinuidadAhoraRoute = ContinuidadAhoraRouteImport.update({
  id: '/ahora',
  path: '/ahora',
  getParentRoute: () => ContinuidadRoute,
} as any)
const ContinuidadClimaRoute = ContinuidadClimaRouteImport.update({
  id: '/clima',
  path: '/clima',
  getParentRoute: () => ContinuidadRoute,
} as any)
const ContinuidadConfigRoute = ContinuidadConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ContinuidadRoute,
} as any)
const ContinuidadHistorialRoute = ContinuidadHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => ContinuidadRoute,
} as any)
const ContinuidadMapaRoute = ContinuidadMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => ContinuidadRoute,
} as any)
const ContinuidadPlanRoute = ContinuidadPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => ContinuidadRoute,
} as any)
const ContinuidadTransporteRoute = ContinuidadTransporteRouteImport.update({
  id: '/transporte',
  path: '/transporte',
  getParentRoute: () => ContinuidadRoute,
} as any)
const ContinuidadTurnoRoute = ContinuidadTurnoRouteImport.update({
  id: '/turno',
  path: '/turno',
  getParentRoute: () => ContinuidadRoute,
} as any)
const FichaIdRoute = FichaIdRouteImport.update({
  id: '/ficha/$id',
  path: '/ficha/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InternadosIndexRoute = InternadosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InternadosRoute,
} as any)
const InternadosSlugRoute = InternadosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InternadosRoute,
} as any)
const InternadosAlertasRoute = InternadosAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => InternadosRoute,
} as any)
const InternadosCamasRoute = InternadosCamasRouteImport.update({
  id: '/camas',
  path: '/camas',
  getParentRoute: () => InternadosRoute,
} as any)
const InternadosCapturaRoute = InternadosCapturaRouteImport.update({
  id: '/captura',
  path: '/captura',
  getParentRoute: () => InternadosRoute,
} as any)
const InternadosPacientesRoute = InternadosPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => InternadosRoute,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiciosRoute,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServiciosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archivo': typeof ArchivoRouteWithChildren
  '/cambios': typeof CambiosRoute
  '/complementos': typeof ComplementosRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/continuidad': typeof ContinuidadRouteWithChildren
  '/internados': typeof InternadosRouteWithChildren
  '/personal-mapa': typeof PersonalMapaRoute
  '/plantel': typeof PlantelRoute
  '/salud': typeof SaludRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/archivo/$id': typeof ArchivoIdRoute
  '/continuidad/ahora': typeof ContinuidadAhoraRoute
  '/continuidad/clima': typeof ContinuidadClimaRoute
  '/continuidad/config': typeof ContinuidadConfigRoute
  '/continuidad/historial': typeof ContinuidadHistorialRoute
  '/continuidad/mapa': typeof ContinuidadMapaRoute
  '/continuidad/plan': typeof ContinuidadPlanRoute
  '/continuidad/transporte': typeof ContinuidadTransporteRoute
  '/continuidad/turno': typeof ContinuidadTurnoRoute
  '/ficha/$id': typeof FichaIdRoute
  '/internados/$slug': typeof InternadosSlugRoute
  '/internados/alertas': typeof InternadosAlertasRoute
  '/internados/camas': typeof InternadosCamasRoute
  '/internados/captura': typeof InternadosCapturaRoute
  '/internados/pacientes': typeof InternadosPacientesRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/archivo/': typeof ArchivoIndexRoute
  '/continuidad/': typeof ContinuidadIndexRoute
  '/internados/': typeof InternadosIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cambios': typeof CambiosRoute
  '/complementos': typeof ComplementosRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/personal-mapa': typeof PersonalMapaRoute
  '/plantel': typeof PlantelRoute
  '/salud': typeof SaludRoute
  '/archivo/$id': typeof ArchivoIdRoute
  '/continuidad/ahora': typeof ContinuidadAhoraRoute
  '/continuidad/clima': typeof ContinuidadClimaRoute
  '/continuidad/config': typeof ContinuidadConfigRoute
  '/continuidad/historial': typeof ContinuidadHistorialRoute
  '/continuidad/mapa': typeof ContinuidadMapaRoute
  '/continuidad/plan': typeof ContinuidadPlanRoute
  '/continuidad/transporte': typeof ContinuidadTransporteRoute
  '/continuidad/turno': typeof ContinuidadTurnoRoute
  '/ficha/$id': typeof FichaIdRoute
  '/internados/$slug': typeof InternadosSlugRoute
  '/internados/alertas': typeof InternadosAlertasRoute
  '/internados/camas': typeof InternadosCamasRoute
  '/internados/captura': typeof InternadosCapturaRoute
  '/internados/pacientes': typeof InternadosPacientesRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/archivo': typeof ArchivoIndexRoute
  '/continuidad': typeof ContinuidadIndexRoute
  '/internados': typeof InternadosIndexRoute
  '/servicios': typeof ServiciosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archivo': typeof ArchivoRouteWithChildren
  '/cambios': typeof CambiosRoute
  '/complementos': typeof ComplementosRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/continuidad': typeof ContinuidadRouteWithChildren
  '/internados': typeof InternadosRouteWithChildren
  '/personal-mapa': typeof PersonalMapaRoute
  '/plantel': typeof PlantelRoute
  '/salud': typeof SaludRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/archivo/$id': typeof ArchivoIdRoute
  '/continuidad/ahora': typeof ContinuidadAhoraRoute
  '/continuidad/clima': typeof ContinuidadClimaRoute
  '/continuidad/config': typeof ContinuidadConfigRoute
  '/continuidad/historial': typeof ContinuidadHistorialRoute
  '/continuidad/mapa': typeof ContinuidadMapaRoute
  '/continuidad/plan': typeof ContinuidadPlanRoute
  '/continuidad/transporte': typeof ContinuidadTransporteRoute
  '/continuidad/turno': typeof ContinuidadTurnoRoute
  '/ficha/$id': typeof FichaIdRoute
  '/internados/$slug': typeof InternadosSlugRoute
  '/internados/alertas': typeof InternadosAlertasRoute
  '/internados/camas': typeof InternadosCamasRoute
  '/internados/captura': typeof InternadosCapturaRoute
  '/internados/pacientes': typeof InternadosPacientesRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/archivo/': typeof ArchivoIndexRoute
  '/continuidad/': typeof ContinuidadIndexRoute
  '/internados/': typeof InternadosIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archivo'
    | '/cambios'
    | '/complementos'
    | '/comunicaciones'
    | '/continuidad'
    | '/internados'
    | '/personal-mapa'
    | '/plantel'
    | '/salud'
    | '/servicios'
    | '/archivo/$id'
    | '/continuidad/ahora'
    | '/continuidad/clima'
    | '/continuidad/config'
    | '/continuidad/historial'
    | '/continuidad/mapa'
    | '/continuidad/plan'
    | '/continuidad/transporte'
    | '/continuidad/turno'
    | '/ficha/$id'
    | '/internados/$slug'
    | '/internados/alertas'
    | '/internados/camas'
    | '/internados/captura'
    | '/internados/pacientes'
    | '/servicios/$slug'
    | '/archivo/'
    | '/continuidad/'
    | '/internados/'
    | '/servicios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cambios'
    | '/complementos'
    | '/comunicaciones'
    | '/personal-mapa'
    | '/plantel'
    | '/salud'
    | '/archivo/$id'
    | '/continuidad/ahora'
    | '/continuidad/clima'
    | '/continuidad/config'
    | '/continuidad/historial'
    | '/continuidad/mapa'
    | '/continuidad/plan'
    | '/continuidad/transporte'
    | '/continuidad/turno'
    | '/ficha/$id'
    | '/internados/$slug'
    | '/internados/alertas'
    | '/internados/camas'
    | '/internados/captura'
    | '/internados/pacientes'
    | '/servicios/$slug'
    | '/archivo'
    | '/continuidad'
    | '/internados'
    | '/servicios'
  id:
    | '__root__'
    | '/'
    | '/archivo'
    | '/cambios'
    | '/complementos'
    | '/comunicaciones'
    | '/continuidad'
    | '/internados'
    | '/personal-mapa'
    | '/plantel'
    | '/salud'
    | '/servicios'
    | '/archivo/$id'
    | '/continuidad/ahora'
    | '/continuidad/clima'
    | '/continuidad/config'
    | '/continuidad/historial'
    | '/continuidad/mapa'
    | '/continuidad/plan'
    | '/continuidad/transporte'
    | '/continuidad/turno'
    | '/ficha/$id'
    | '/internados/$slug'
    | '/internados/alertas'
    | '/internados/camas'
    | '/internados/captura'
    | '/internados/pacientes'
    | '/servicios/$slug'
    | '/archivo/'
    | '/continuidad/'
    | '/internados/'
    | '/servicios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivoRoute: typeof ArchivoRouteWithChildren
  CambiosRoute: typeof CambiosRoute
  ComplementosRoute: typeof ComplementosRoute
  ComunicacionesRoute: typeof ComunicacionesRoute
  ContinuidadRoute: typeof ContinuidadRouteWithChildren
  InternadosRoute: typeof InternadosRouteWithChildren
  PersonalMapaRoute: typeof PersonalMapaRoute
  PlantelRoute: typeof PlantelRoute
  SaludRoute: typeof SaludRoute
  ServiciosRoute: typeof ServiciosRouteWithChildren
  FichaIdRoute: typeof FichaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archivo': {
      id: '/archivo'
      path: '/archivo'
      fullPath: '/archivo'
      preLoaderRoute: typeof ArchivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambios': {
      id: '/cambios'
      path: '/cambios'
      fullPath: '/cambios'
      preLoaderRoute: typeof CambiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complementos': {
      id: '/complementos'
      path: '/complementos'
      fullPath: '/complementos'
      preLoaderRoute: typeof ComplementosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicaciones': {
      id: '/comunicaciones'
      path: '/comunicaciones'
      fullPath: '/comunicaciones'
      preLoaderRoute: typeof ComunicacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continuidad': {
      id: '/continuidad'
      path: '/continuidad'
      fullPath: '/continuidad'
      preLoaderRoute: typeof ContinuidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internados': {
      id: '/internados'
      path: '/internados'
      fullPath: '/internados'
      preLoaderRoute: typeof InternadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-mapa': {
      id: '/personal-mapa'
      path: '/personal-mapa'
      fullPath: '/personal-mapa'
      preLoaderRoute: typeof PersonalMapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantel': {
      id: '/plantel'
      path: '/plantel'
      fullPath: '/plantel'
      preLoaderRoute: typeof PlantelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salud': {
      id: '/salud'
      path: '/salud'
      fullPath: '/salud'
      preLoaderRoute: typeof SaludRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archivo/': {
      id: '/archivo/'
      path: '/'
      fullPath: '/archivo/'
      preLoaderRoute: typeof ArchivoIndexRouteImport
      parentRoute: typeof ArchivoRoute
    }
    '/archivo/$id': {
      id: '/archivo/$id'
      path: '/$id'
      fullPath: '/archivo/$id'
      preLoaderRoute: typeof ArchivoIdRouteImport
      parentRoute: typeof ArchivoRoute
    }
    '/continuidad/': {
      id: '/continuidad/'
      path: '/'
      fullPath: '/continuidad/'
      preLoaderRoute: typeof ContinuidadIndexRouteImport
      parentRoute: typeof ContinuidadRoute
    }
    '/continuidad/ahora': {
      id: '/continuidad/ahora'
      path: '/ahora'
      fullPath: '/continuidad/ahora'
      preLoaderRoute: typeof ContinuidadAhoraRouteImport
      parentRoute: typeof ContinuidadRoute
    }
    '/continuidad/clima': {
      id: '/continuidad/clima'
      path: '/clima'
      fullPath: '/continuidad/clima'
      preLoaderRoute: typeof ContinuidadClimaRouteImport
      parentRoute: typeof ContinuidadRoute
    }
    '/continuidad/config': {
      id: '/continuidad/config'
      path: '/config'
      fullPath: '/continuidad/config'
      preLoaderRoute: typeof ContinuidadConfigRouteImport
      parentRoute: typeof ContinuidadRoute
    }
    '/continuidad/historial': {
      id: '/continuidad/historial'
      path: '/historial'
      fullPath: '/continuidad/historial'
      preLoaderRoute: typeof ContinuidadHistorialRouteImport
      parentRoute: typeof ContinuidadRoute
    }
    '/continuidad/mapa': {
      id: '/continuidad/mapa'
      path: '/mapa'
      fullPath: '/continuidad/mapa'
      preLoaderRoute: typeof ContinuidadMapaRouteImport
      parentRoute: typeof ContinuidadRoute
    }
    '/continuidad/plan': {
      id: '/continuidad/plan'
      path: '/plan'
      fullPath: '/continuidad/plan'
      preLoaderRoute: typeof ContinuidadPlanRouteImport
      parentRoute: typeof ContinuidadRoute
    }
    '/continuidad/transporte': {
      id: '/continuidad/transporte'
      path: '/transporte'
      fullPath: '/continuidad/transporte'
      preLoaderRoute: typeof ContinuidadTransporteRouteImport
      parentRoute: typeof ContinuidadRoute
    }
    '/continuidad/turno': {
      id: '/continuidad/turno'
      path: '/turno'
      fullPath: '/continuidad/turno'
      preLoaderRoute: typeof ContinuidadTurnoRouteImport
      parentRoute: typeof ContinuidadRoute
    }
    '/ficha/$id': {
      id: '/ficha/$id'
      path: '/ficha/$id'
      fullPath: '/ficha/$id'
      preLoaderRoute: typeof FichaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internados/': {
      id: '/internados/'
      path: '/'
      fullPath: '/internados/'
      preLoaderRoute: typeof InternadosIndexRouteImport
      parentRoute: typeof InternadosRoute
    }
    '/internados/$slug': {
      id: '/internados/$slug'
      path: '/$slug'
      fullPath: '/internados/$slug'
      preLoaderRoute: typeof InternadosSlugRouteImport
      parentRoute: typeof InternadosRoute
    }
    '/internados/alertas': {
      id: '/internados/alertas'
      path: '/alertas'
      fullPath: '/internados/alertas'
      preLoaderRoute: typeof InternadosAlertasRouteImport
      parentRoute: typeof InternadosRoute
    }
    '/internados/camas': {
      id: '/internados/camas'
      path: '/camas'
      fullPath: '/internados/camas'
      preLoaderRoute: typeof InternadosCamasRouteImport
      parentRoute: typeof InternadosRoute
    }
    '/internados/captura': {
      id: '/internados/captura'
      path: '/captura'
      fullPath: '/internados/captura'
      preLoaderRoute: typeof InternadosCapturaRouteImport
      parentRoute: typeof InternadosRoute
    }
    '/internados/pacientes': {
      id: '/internados/pacientes'
      path: '/pacientes'
      fullPath: '/internados/pacientes'
      preLoaderRoute: typeof InternadosPacientesRouteImport
      parentRoute: typeof InternadosRoute
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof ServiciosRoute
    }
  }
}

interface ArchivoRouteChildren {
  ArchivoIdRoute: typeof ArchivoIdRoute
  ArchivoIndexRoute: typeof ArchivoIndexRoute
}

const ArchivoRouteChildren: ArchivoRouteChildren = {
  ArchivoIdRoute: ArchivoIdRoute,
  ArchivoIndexRoute: ArchivoIndexRoute,
}

const ArchivoRouteWithChildren =
  ArchivoRoute._addFileChildren(ArchivoRouteChildren)

interface ContinuidadRouteChildren {
  ContinuidadAhoraRoute: typeof ContinuidadAhoraRoute
  ContinuidadClimaRoute: typeof ContinuidadClimaRoute
  ContinuidadConfigRoute: typeof ContinuidadConfigRoute
  ContinuidadHistorialRoute: typeof ContinuidadHistorialRoute
  ContinuidadMapaRoute: typeof ContinuidadMapaRoute
  ContinuidadPlanRoute: typeof ContinuidadPlanRoute
  ContinuidadTransporteRoute: typeof ContinuidadTransporteRoute
  ContinuidadTurnoRoute: typeof ContinuidadTurnoRoute
  ContinuidadIndexRoute: typeof ContinuidadIndexRoute
}

const ContinuidadRouteChildren: ContinuidadRouteChildren = {
  ContinuidadAhoraRoute: ContinuidadAhoraRoute,
  ContinuidadClimaRoute: ContinuidadClimaRoute,
  ContinuidadConfigRoute: ContinuidadConfigRoute,
  ContinuidadHistorialRoute: ContinuidadHistorialRoute,
  ContinuidadMapaRoute: ContinuidadMapaRoute,
  ContinuidadPlanRoute: ContinuidadPlanRoute,
  ContinuidadTransporteRoute: ContinuidadTransporteRoute,
  ContinuidadTurnoRoute: ContinuidadTurnoRoute,
  ContinuidadIndexRoute: ContinuidadIndexRoute,
}

const ContinuidadRouteWithChildren = ContinuidadRoute._addFileChildren(
  ContinuidadRouteChildren,
)

interface InternadosRouteChildren {
  InternadosSlugRoute: typeof InternadosSlugRoute
  InternadosAlertasRoute: typeof InternadosAlertasRoute
  InternadosCamasRoute: typeof InternadosCamasRoute
  InternadosCapturaRoute: typeof InternadosCapturaRoute
  InternadosPacientesRoute: typeof InternadosPacientesRoute
  InternadosIndexRoute: typeof InternadosIndexRoute
}

const InternadosRouteChildren: InternadosRouteChildren = {
  InternadosSlugRoute: InternadosSlugRoute,
  InternadosAlertasRoute: InternadosAlertasRoute,
  InternadosCamasRoute: InternadosCamasRoute,
  InternadosCapturaRoute: InternadosCapturaRoute,
  InternadosPacientesRoute: InternadosPacientesRoute,
  InternadosIndexRoute: InternadosIndexRoute,
}

const InternadosRouteWithChildren = InternadosRoute._addFileChildren(
  InternadosRouteChildren,
)

interface ServiciosRouteChildren {
  ServiciosSlugRoute: typeof ServiciosSlugRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

const ServiciosRouteChildren: ServiciosRouteChildren = {
  ServiciosSlugRoute: ServiciosSlugRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}

const ServiciosRouteWithChildren = ServiciosRoute._addFileChildren(
  ServiciosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivoRoute: ArchivoRouteWithChildren,
  CambiosRoute: CambiosRoute,
  ComplementosRoute: ComplementosRoute,
  ComunicacionesRoute: ComunicacionesRoute,
  ContinuidadRoute: ContinuidadRouteWithChildren,
  InternadosRoute: InternadosRouteWithChildren,
  PersonalMapaRoute: PersonalMapaRoute,
  PlantelRoute: PlantelRoute,
  SaludRoute: SaludRoute,
  ServiciosRoute: ServiciosRouteWithChildren,
  FichaIdRoute: FichaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
